
title: "The True Cost of ICT: From Materiality to Techno-Solutionism"
description: "A workshop at [ICT4s 2024](https://conf.researchr.org/home/ict4s-2024)."

navbar-links:
  Workshop Description: "index.html"
  Call for Contributions: "index.html"
  Organisers: "index.html"

author:
  name: Jan Tobias Muehlberg

theme: jekyll-theme-slate

